const TRIGGER_DB_SUFFIX = 'cloudanttrigger';
const DEFAULT_TRIGGER_COUNT = -1;
const RETRIES_BEFORE_DELETE = 10;

module.exports = {
    TRIGGER_DB_SUFFIX: TRIGGER_DB_SUFFIX,
    DEFAULT_TRIGGER_COUNT: DEFAULT_TRIGGER_COUNT,
    RETRIES_BEFORE_DELETE: RETRIES_BEFORE_DELETE
};
